apiVersion: v1
kind: Secret
metadata:
  name: {{ include "medanki-backend.fullname" . }}-secrets
  labels:
    {{- include "medanki-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ required "secrets.databaseUrl required" .Values.secrets.databaseUrl | quote }}
  jwt-signing-key: {{ required "secrets.jwtSigningKey required" .Values.secrets.jwtSigningKey | quote }}
  {{- if .Values.secrets.sentryDsn }}
  sentry-dsn: {{ .Values.secrets.sentryDsn | quote }}
  {{- end }}
