apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  labels:
    app: cms
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
        tier: web
    spec:
      containers:
        - name: cms
          image: medanki/cms:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "https://api.medanki-dz.com"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
