apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medanki-staging

resources:
  - ../../base

namePrefix: stg-

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: cms
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

configMapGenerator:
  - name: medanki-config
    behavior: merge
    literals:
      - log-level=debug
      - feature-r2-upload=false
